"""
Agent Factory - Generates new Synapse tracker agents from safe templates.

Claude (via smart_chat.py) calls create_agent() with parameters, and this
module writes a complete, self-healing agent file. All generated agents
share the same DB schema, so the chat can log entries into any of them.
"""

import os
import re
import sys
import json
import sqlite3
import subprocess
from datetime import date, datetime

REGISTRY_PATH = "factory_registry.json"

# ---------------------------------------------------------------
# The template. Uses __TOKENS__ replaced at generation time.
# ---------------------------------------------------------------

AGENT_TEMPLATE = '''"""
__AGENT_NAME__ - Auto-generated by Synapse Agent Factory.
Tracks: __DESCRIPTION__ (unit: __UNIT__)

Usage:
    python __FILE_NAME__ log <amount> <category>
    python __FILE_NAME__ today
    python __FILE_NAME__ run
"""

import sys
import sqlite3
import asyncio
from datetime import date
from agent_sdk import AgentSDK
from structured_logger import StructuredLogger

AGENT_ID = "__AGENT_ID__"
DB_PATH = "factory___AGENT_ID_SNAKE__.db"
UNIT = "__UNIT__"
VALID_CATEGORIES = __CATEGORIES__


class TrackerAgent:
    def __init__(self):
        self.agent_id = AGENT_ID
        self.logger = StructuredLogger(agent_id=AGENT_ID)
        self.sdk = AgentSDK(
            agent_id=AGENT_ID,
            ingestion_url="http://localhost:5000",
            tags={"agent_type": "factory_tracker", "service": "__AGENT_NAME__"},
        )
        conn = sqlite3.connect(DB_PATH)
        conn.execute("PRAGMA journal_mode=WAL")
        conn.execute("""
            CREATE TABLE IF NOT EXISTS entries (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                log_date TEXT NOT NULL,
                category TEXT NOT NULL,
                amount REAL NOT NULL,
                logged_at TEXT DEFAULT CURRENT_TIMESTAMP
            )
        """)
        conn.commit()
        conn.close()

    def log_entry(self, amount, category):
        category = category.lower().strip()
        if VALID_CATEGORIES and category not in VALID_CATEGORIES:
            raise ValueError(f"Category must be one of: {', '.join(VALID_CATEGORIES)}")
        if amount <= 0:
            raise ValueError("Amount must be positive")
        conn = sqlite3.connect(DB_PATH)
        conn.execute(
            "INSERT INTO entries (log_date, category, amount) VALUES (?, ?, ?)",
            (date.today().isoformat(), category, amount),
        )
        conn.commit()
        conn.close()
        self.logger.log_event("entry_logged", category=category, amount=amount)
        return self.get_today()

    def get_today(self):
        conn = sqlite3.connect(DB_PATH)
        rows = conn.execute(
            "SELECT category, SUM(amount), COUNT(*) FROM entries "
            "WHERE log_date = ? GROUP BY category",
            (date.today().isoformat(),),
        ).fetchall()
        conn.close()
        by_cat = {c: round(t, 2) for c, t, _ in rows}
        return {
            "date": date.today().isoformat(),
            "unit": UNIT,
            "total": round(sum(by_cat.values()), 2),
            "by_category": by_cat,
            "entries": sum(n for _, _, n in rows),
        }

    def register(self):
        self.sdk.register({
            "name": "__AGENT_NAME__",
            "type": "factory_tracker",
            "description": "__DESCRIPTION__",
            "unit": UNIT,
            "version": "1.0.0",
        })

    def do_work(self):
        totals = self.get_today()
        metrics = {
            "status": "HEALTHY",
            "tasks_completed": 1,
            "total_today": totals["total"],
            "entries_today": totals["entries"],
        }
        for cat, amt in totals["by_category"].items():
            metrics[f"amt_{cat}"] = amt
        self.sdk.send_metrics(metrics)
        self.logger.log_event("totals_reported", total=totals["total"])


def main():
    agent = TrackerAgent()
    if len(sys.argv) < 2:
        print(__doc__)
        return
    cmd = sys.argv[1].lower()
    if cmd == "log" and len(sys.argv) == 4:
        try:
            t = agent.log_entry(float(sys.argv[2]), sys.argv[3])
            print(f"Logged {sys.argv[2]} {UNIT} of {sys.argv[3]}. Today: {t['total']} {UNIT}")
        except ValueError as e:
            print(f"Error: {e}")
    elif cmd == "today":
        print(json.dumps(agent.get_today(), indent=2))
    elif cmd == "run":
        from healing_wrapper import make_healable, run_with_healing
        agent.register()
        healable = make_healable(agent, agent_id=agent.agent_id)
        print(f"__AGENT_NAME__ running with self-healing (Ctrl+C to stop)")
        asyncio.run(run_with_healing(healable, work_fn=agent.do_work, work_interval_seconds=60))
    else:
        print(__doc__)


if __name__ == "__main__":
    import json
    main()
'''


# ---------------------------------------------------------------
# Factory functions (called by smart_chat tools)
# ---------------------------------------------------------------

def _snake(agent_id: str) -> str:
    return re.sub(r"[^a-z0-9_]", "_", agent_id.lower().replace("-", "_"))


def _load_registry() -> dict:
    if os.path.exists(REGISTRY_PATH):
        with open(REGISTRY_PATH) as f:
            return json.load(f)
    return {}


def _save_registry(reg: dict):
    with open(REGISTRY_PATH, "w") as f:
        json.dump(reg, f, indent=2)


def create_agent(agent_id: str, name: str, description: str, unit: str, categories: list) -> dict:
    """Generate a new tracker agent file from the template."""
    if not re.match(r"^[a-z0-9\-]{3,40}$", agent_id):
        return {"error": "agent_id must be lowercase letters/numbers/hyphens, 3-40 chars"}

    reg = _load_registry()
    if agent_id in reg:
        return {"error": f"Agent '{agent_id}' already exists", "file": reg[agent_id]["file"]}

    snake = _snake(agent_id)
    file_name = f"{snake}.py"
    if os.path.exists(file_name):
        return {"error": f"File {file_name} already exists"}

    categories = [c.lower().strip() for c in categories] if categories else []

    code = (AGENT_TEMPLATE
            .replace("__AGENT_ID__", agent_id)
            .replace("__AGENT_ID_SNAKE__", snake)
            .replace("__AGENT_NAME__", name)
            .replace("__DESCRIPTION__", description)
            .replace("__UNIT__", unit)
            .replace("__FILE_NAME__", file_name)
            .replace("__CATEGORIES__", json.dumps(categories)))

    with open(file_name, "w") as f:
        f.write(code)

    reg[agent_id] = {
        "name": name,
        "description": description,
        "unit": unit,
        "categories": categories,
        "file": file_name,
        "created_at": datetime.now().isoformat(),
    }
    _save_registry(reg)

    return {"created": True, "agent_id": agent_id, "file": file_name,
            "unit": unit, "categories": categories}


def list_agents() -> dict:
    """List all factory-created agents."""
    return {"agents": _load_registry()}


def start_agent(agent_id: str) -> dict:
    """Launch a factory agent as a background process (with self-healing)."""
    reg = _load_registry()
    if agent_id not in reg:
        return {"error": f"Unknown agent '{agent_id}'. Create it first."}
    file = reg[agent_id]["file"]
    proc = subprocess.Popen(
        [sys.executable, file, "run"],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    return {"started": True, "agent_id": agent_id, "pid": proc.pid,
            "note": "Agent running in background, registering with Synapse."}


def log_entry(agent_id: str, amount: float, category: str) -> dict:
    """Log an entry into any factory agent's database (shared schema)."""
    reg = _load_registry()
    if agent_id not in reg:
        return {"error": f"Unknown agent '{agent_id}'"}
    info = reg[agent_id]
    cats = info.get("categories", [])
    category = category.lower().strip()
    if cats and category not in cats:
        return {"error": f"Category must be one of: {', '.join(cats)}"}
    if amount <= 0:
        return {"error": "Amount must be positive"}

    db = f"factory_{_snake(agent_id)}.db"
    conn = sqlite3.connect(db)
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("""
        CREATE TABLE IF NOT EXISTS entries (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            log_date TEXT NOT NULL,
            category TEXT NOT NULL,
            amount REAL NOT NULL,
            logged_at TEXT DEFAULT CURRENT_TIMESTAMP
        )
    """)
    conn.execute(
        "INSERT INTO entries (log_date, category, amount) VALUES (?, ?, ?)",
        (date.today().isoformat(), category, amount),
    )
    conn.commit()
    conn.close()
    return {"logged": True, **get_today(agent_id)}


def get_today(agent_id: str) -> dict:
    """Get today's totals for any factory agent."""
    reg = _load_registry()
    if agent_id not in reg:
        return {"error": f"Unknown agent '{agent_id}'"}
    db = f"factory_{_snake(agent_id)}.db"
    if not os.path.exists(db):
        return {"date": date.today().isoformat(), "unit": reg[agent_id]["unit"],
                "total": 0, "by_category": {}, "entries": 0}
    conn = sqlite3.connect(db)
    rows = conn.execute(
        "SELECT category, SUM(amount), COUNT(*) FROM entries "
        "WHERE log_date = ? GROUP BY category",
        (date.today().isoformat(),),
    ).fetchall()
    conn.close()
    by_cat = {c: round(t, 2) for c, t, _ in rows}
    return {"date": date.today().isoformat(), "unit": reg[agent_id]["unit"],
            "total": round(sum(by_cat.values()), 2), "by_category": by_cat,
            "entries": sum(n for _, _, n in rows)}