"""
Water Intake Tracker - Auto-generated by Synapse Agent Factory.
Tracks: Tracks daily water intake in liters (unit: liters)

Usage:
    python water_tracker.py log <amount> <category>
    python water_tracker.py today
    python water_tracker.py run
"""

import sys
import sqlite3
import asyncio
from datetime import date
from agent_sdk import AgentSDK
from structured_logger import StructuredLogger

AGENT_ID = "water-tracker"
DB_PATH = "factory_water_tracker.db"
UNIT = "liters"
VALID_CATEGORIES = []


class TrackerAgent:
    def __init__(self):
        self.agent_id = AGENT_ID
        self.logger = StructuredLogger(agent_id=AGENT_ID)
        self.sdk = AgentSDK(
            agent_id=AGENT_ID,
            ingestion_url="http://localhost:5000",
            tags={"agent_type": "factory_tracker", "service": "Water Intake Tracker"},
        )
        conn = sqlite3.connect(DB_PATH)
        conn.execute("PRAGMA journal_mode=WAL")
        conn.execute("""
            CREATE TABLE IF NOT EXISTS entries (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                log_date TEXT NOT NULL,
                category TEXT NOT NULL,
                amount REAL NOT NULL,
                logged_at TEXT DEFAULT CURRENT_TIMESTAMP
            )
        """)
        conn.commit()
        conn.close()

    def log_entry(self, amount, category):
        category = category.lower().strip()
        if VALID_CATEGORIES and category not in VALID_CATEGORIES:
            raise ValueError(f"Category must be one of: {', '.join(VALID_CATEGORIES)}")
        if amount <= 0:
            raise ValueError("Amount must be positive")
        conn = sqlite3.connect(DB_PATH)
        conn.execute(
            "INSERT INTO entries (log_date, category, amount) VALUES (?, ?, ?)",
            (date.today().isoformat(), category, amount),
        )
        conn.commit()
        conn.close()
        self.logger.log_event("entry_logged", category=category, amount=amount)
        return self.get_today()

    def get_today(self):
        conn = sqlite3.connect(DB_PATH)
        rows = conn.execute(
            "SELECT category, SUM(amount), COUNT(*) FROM entries "
            "WHERE log_date = ? GROUP BY category",
            (date.today().isoformat(),),
        ).fetchall()
        conn.close()
        by_cat = {c: round(t, 2) for c, t, _ in rows}
        return {
            "date": date.today().isoformat(),
            "unit": UNIT,
            "total": round(sum(by_cat.values()), 2),
            "by_category": by_cat,
            "entries": sum(n for _, _, n in rows),
        }

    def register(self):
        self.sdk.register({
            "name": "Water Intake Tracker",
            "type": "factory_tracker",
            "description": "Tracks daily water intake in liters",
            "unit": UNIT,
            "version": "1.0.0",
        })

    def do_work(self):
        totals = self.get_today()
        metrics = {
            "status": "HEALTHY",
            "tasks_completed": 1,
            "total_today": totals["total"],
            "entries_today": totals["entries"],
        }
        for cat, amt in totals["by_category"].items():
            metrics[f"amt_{cat}"] = amt
        self.sdk.send_metrics(metrics)
        self.logger.log_event("totals_reported", total=totals["total"])


def main():
    agent = TrackerAgent()
    if len(sys.argv) < 2:
        print(__doc__)
        return
    cmd = sys.argv[1].lower()
    if cmd == "log" and len(sys.argv) == 4:
        try:
            t = agent.log_entry(float(sys.argv[2]), sys.argv[3])
            print(f"Logged {sys.argv[2]} {UNIT} of {sys.argv[3]}. Today: {t['total']} {UNIT}")
        except ValueError as e:
            print(f"Error: {e}")
    elif cmd == "today":
        print(json.dumps(agent.get_today(), indent=2))
    elif cmd == "run":
        from healing_wrapper import make_healable, run_with_healing
        agent.register()
        healable = make_healable(agent, agent_id=agent.agent_id)
        print(f"Water Intake Tracker running with self-healing (Ctrl+C to stop)")
        asyncio.run(run_with_healing(healable, work_fn=agent.do_work, work_interval_seconds=60))
    else:
        print(__doc__)


if __name__ == "__main__":
    import json
    main()
